version: "3.7"

services:
  db:
    image: "postgres:latest" ### 14-alpine
    container_name: postgres_service
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mate_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
        sh -c "python3 manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - db

volumes:
    service_data:
      driver: local
